#!/usr/bin/env sh
echo "EXECUTED COMMAND:"
echo "rm -Rf ./node_modules/ && npm install && ./node_modules/.bin/nightwatch --env firefox $1"
rm -Rf ./node_modules/ && npm install && ./node_modules/.bin/nightwatch --env firefox $1
